In [1]:
!pip install opensignalsreader

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 2.3 MB/s eta 0:00:00


In [3]:
!pip install biosignalsnotebooks

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 46.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of biosignalsnotebooks to determine which version is compatible with other requirements. This could take a while.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.1/39.1 MB 17.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 59.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 50.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.3/36.3 MB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 2.9 MB/s eta 

In [1]:
# Package used for loading data from the input text file
from numpy import loadtxt

# biosignalsnotebooks python package
import biosignalsnotebooks as bsnb
data = loadtxt("SampleEOG_Horizontal_Eye_Movement.txt")

In [15]:
# Package used for loading data from the input text file
from numpy import loadtxt

# biosignalsnotebooks python package
import biosignalsnotebooks as bsnb
data = loadtxt("opensignals_0007800f3067_2025-03-20_19-44-41.txt")

In [16]:
print(data)

[[0.0000e+00 0.0000e+00 3.2855e+04]
 [1.0000e+00 0.0000e+00 3.2848e+04]
 [2.0000e+00 0.0000e+00 3.2844e+04]
 ...
 [3.7047e+04 0.0000e+00 3.2830e+04]
 [3.7048e+04 0.0000e+00 3.2850e+04]
 [3.7049e+04 0.0000e+00 3.2806e+04]]


In [17]:
sampling_rate = 1000

In [18]:
time = bsnb.generate_time(data, sampling_rate)

In [19]:
print (data)

[[0.0000e+00 0.0000e+00 3.2855e+04]
 [1.0000e+00 0.0000e+00 3.2848e+04]
 [2.0000e+00 0.0000e+00 3.2844e+04]
 ...
 [3.7047e+04 0.0000e+00 3.2830e+04]
 [3.7048e+04 0.0000e+00 3.2850e+04]
 [3.7049e+04 0.0000e+00 3.2806e+04]]


In [20]:
channel_column = 2

In [21]:
bsnb.plot(time, data[:, channel_column])

In [22]:
# Base packages used in OpenSignals Tools Notebooks for plotting data
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.layouts import gridplot
from bokeh.models.tools import *
output_notebook(hide_banner=True)

# Package for ensuring operations in arrays
from numpy import average, linspace, random

# Own opensignalstools package needed here for applying the default OpenSignals styles and for loading data from an acquisition
# file.
import biosignalsnotebooks as bsnb

In [23]:
# Load of data from a remote source
data, header = bsnb.load("/content/opensignals_0007800f3067_2025-03-20_19-44-41.h5", get_header=True)

In [24]:
print ("\033[1mHeader:\n\033[0m" + str(header) + "\n\033[1mData:\033[0m\n" + str(data))

Header:
{'channels': array([1], dtype=int32), 'comments': '', 'date': '2025-3-20', 'device': 'biosignalspluxsolo', 'device connection': 'BTH00:07:80:0F:30:67', 'device name': '00:07:80:0F:30:67', 'digital IO': array([0, 1], dtype=int32), 'firmware version': 257, 'resolution': array([16], dtype=int32), 'sampling rate': 1000, 'sync interval': 2, 'time': '19:44:47.308', 'sensor': ['RAW'], 'column labels': {1: 'channel_1'}}
Data:
{'CH1': array([32855, 32848, 32844, ..., 32830, 32850, 32806], dtype=uint32)}


In [25]:
signal = data["CH1"]
time = bsnb.generate_time(signal, header["sampling rate"])

In [26]:
# Noise samples and change of the baseline level
baseline = average(signal)
baseline_shift = 0.50 * baseline
data_noise = signal + random.normal(0, 1000, len(signal)) + baseline_shift

In [27]:
bsnb.plot([time, time], [signal, data_noise], legend_label=["Original Data", "Noisy Data"], y_axis_label=["Raw Data", "Raw Data"], x_axis_label="Time (s)")